### ISSUE TITLE
Replace `conf.Settings.Path` with `conf.Build.publish`

### ISSUE THREAD

**Issue by zanona** [netlify/netlifyctl#57]
Hey guys,
the previous version of `netlify.toml` has:

```toml
[build]
  publish = 'dist/'
```

But `netlifyctl` now uses:

```toml
[build]
  publish = 'dist/'
[settings]
  path = 'dist/'
```

Perhaps we could streamline this to avoid redundancy and confusion?

https://github.com/netlify/netlifyctl/blob/e4a6a4d92824cf98e46ef22f26c7ab472b6d292d/commands/deploy/deploy.go#L104-L119
